# Generated by Django 5.2 on 2025-04-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ASRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(choices=[('1', '1. 잉크 및 토너 부족'), ('2', '2. 스캔'), ('3', '3. 출력물이 깨끗하지 않음'), ('4', '4. 에러발생'), ('5', '5. 기타')], max_length=1)),
                ('detail', models.TextField(blank=True, null=True)),
                ('submitter', models.CharField(max_length=50)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
