# Generated by Django 5.2 on 2025-04-16 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('ip_address', models.GenericIPAddressField()),
            ],
        ),
        migrations.AlterField(
            model_name='asrequest',
            name='symptom',
            field=models.CharField(choices=[('1', '1. 잉크 및 토너 부족'), ('2', '2. 스캔'), ('3', '3. 출력물이 깨끗하지 않음'), ('4', '4. 에러발생'), ('5', '5. 기타')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='asrequest',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='printer.deviceinfo'),
        ),
    ]
