# Generated by Django 5.2 on 2025-04-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0002_deviceinfo_alter_asrequest_symptom_asrequest_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinfo',
            name='school_slug',
            field=models.SlugField(max_length=100, null=True),
        ),
    ]
