# Generated by Django 5.2 on 2025-04-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0003_deviceinfo_school_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='asrequest',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
