# Generated by Django 5.2 on 2025-04-18 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0004_asrequest_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='asrequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
