# Generated by Django 5.2 on 2025-04-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printer', '0005_asrequest_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='asrequest',
            name='comment',
            field=models.TextField(blank=True, help_text='관리자 코멘트', null=True),
        ),
    ]
